# Generated by Django 5.1.4 on 2025-01-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
