# Generated by Django 6.0 on 2025-12-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_remove_video_opened_alter_video_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovideomedia',
            name='media_type',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('ERROR', 'ERROR')], default='VIDEO', max_length=255),
            preserve_default=False,
        ),
    ]
