# Generated by Django 5.2.4 on 2025-12-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_audiovideomedia_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiovideomedia',
            name='media_type',
            field=models.CharField(choices=[('VIDEO', 'VIDEO'), ('TRAILER', 'TRAILER')], max_length=255),
        ),
    ]
